name: marketplace
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  bloc: ^6.1.3
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  dotted_border: ^1.0.7
  equatable: ^1.2.6
  flutter_bloc: ^6.1.3
  flutter_icons: ^1.1.0
  flutter_svg: ^0.19.3
  flutter_boxicons: ^2.0.2
  flutter_staggered_grid_view: ^0.3.4
  flutter_webview_plugin: ^0.4.0
  flutter_rating_bar: ^3.2.0
  http: ^0.12.2
  image_picker: ^0.6.7+22
  image_picker_for_web: ^0.1.0+2
  intl: ^0.16.1
  meta: ^1.2.4
  shared_preferences: ^0.5.12+4
  get_storage: ^1.4.0
  shimmer: ^1.1.2
  timeline_tile: ^1.0.0
  cached_network_image: ^2.5.1
  get: ^3.26.0
  carousel_slider: ^3.0.0
  websafe_svg: ^1.1.4+2
  webview_flutter: ^1.0.7
  url_launcher: ^6.0.4
  url_strategy: ^0.2.0
  beamer: ^0.10.5
  encrypt: ^4.1.0
  aligned_dialog: ^0.0.6
  flutter_dotenv: ^3.1.0
  expandable: ^5.0.1
  path: ^1.7.0
  onesignal_flutter: ^2.6.4
  path_provider: ^1.6.28
  image_gallery_saver: ^1.6.8
  permission_handler: ^5.1.0+2
  open_file: ^3.0.3
  package_info_plus: ^0.6.4
  pdf: ^2.1.0
  sticky_headers : ^0.1.8+1
  share_plus: ^2.0.1
  pin_code_fields: ^6.1.0
  pattern_formatter: ^2.0.0
  flutter_html: ^1.1.1
  change_app_package_name: ^0.1.3
  eva_icons_flutter: ^2.0.1
  printing: ^4.0.1
  readmore: ^2.1.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"

dependency_overrides:
  intl: ^0.16.1
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/decorations/
    - images/icons/
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Regular.ttf
        - asset: fonts/inter/Inter-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: fonts/lato/Lato-Regular.ttf
        - asset: fonts/lato/Lato-Light.ttf
        - asset: fonts/lato/Lato-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
